# Generated by Django 3.2 on 2022-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Tom', max_length=100),
            preserve_default=False,
        ),
    ]
