# Generated by Django 3.2 on 2022-01-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='auto_date',
            new_name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
