# Generated by Django 3.2 on 2022-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sponsored_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
