# Generated by Django 3.2 on 2022-01-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_product_sponsored_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sponsored_status',
        ),
        migrations.CreateModel(
            name='Turtles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsored_status', models.BooleanField(blank=True, default=False, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turtles', to='orders.order')),
            ],
        ),
    ]
