# Generated by Django 3.2 on 2022-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_turtles_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='species',
        ),
        migrations.AddField(
            model_name='turtles',
            name='species',
            field=models.CharField(blank=True, choices=[('logger', 'Loggerhead'), ('green', 'Green'), ('leather', 'Leatherback'), ('flat', 'Flatback'), ('hawks', 'Hawksbill'), ('olive', 'Olive Ridley'), ('kemp', "Kemp's Ridley")], max_length=10, null=True),
        ),
    ]
