# Generated by Django 3.2 on 2022-01-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20220118_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtles',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='turtle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turtles', to='orders.turtles'),
        ),
    ]
