# Generated by Django 3.2 on 2022-01-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20220118_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='turtle',
        ),
        migrations.AddField(
            model_name='turtles',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turtle', to='orders.product'),
        ),
    ]
