# Generated by Django 3.2 on 2022-01-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20220118_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtles',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turtle', to='orders.product'),
        ),
    ]
