# Generated by Django 3.2 on 2022-01-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_turtles_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtles',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turtle', to='orders.product'),
        ),
        migrations.AlterField(
            model_name='turtles',
            name='species',
            field=models.CharField(choices=[('logger', 'Loggerhead'), ('green', 'Green'), ('leather', 'Leatherback'), ('flat', 'Flatback'), ('hawks', 'Hawksbill'), ('olive', 'Olive Ridley'), ('kemp', "Kemp's Ridley")], max_length=10),
        ),
        migrations.AlterField(
            model_name='turtles',
            name='sponsored_status',
            field=models.BooleanField(default=False),
        ),
    ]
