# Generated by Django 3.2 on 2022-01-19 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20220119_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtles',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turtle', to='orders.product'),
        ),
    ]
