# Generated by Django 3.2 on 2022-01-20 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_turtles_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtles',
            name='name',
            field=models.CharField(default='Sam', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turtles',
            name='sponsorship_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turtles',
            name='sponsorship_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
