# Generated by Django 3.2 on 2022-01-20 15:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20220120_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtles',
            name='current_location',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='turtles',
            name='tagged_in',
            field=django_countries.fields.CountryField(default='DO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turtles',
            name='turtle_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
