# Generated by Django 3.2 on 2022-01-20 16:16

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20220120_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtles',
            name='sponsorship_end',
            field=models.DateField(default=orders.models.get_sponsorship_end),
        ),
    ]
